In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [1]:
import io
%cd "C:\Users\Admin\Desktop\hackthon\H1N1"

C:\Users\Admin\Desktop\hackthon\H1N1


In [3]:
vaccinetrain=pd.read_csv("training_set_features.csv")

In [6]:
print(vaccinetrain.shape)

(26707, 36)


In [4]:
vaccinetest=pd.read_csv("test_set_features.csv")

In [7]:
print(vaccinetest.shape)

(26708, 36)


In [11]:
vaccine_labels=pd.read_csv("training_set_labels.csv")

In [9]:
impdata=pd.read_csv("impdata.csv")

In [10]:
print(impdata.shape)

(53415, 36)


In [18]:
combinedf=pd.concat([vaccinetrain,vaccinetest],axis=0)

In [23]:
objectcols=combinedf.select_dtypes(include=['object'])
numericcols=combinedf.select_dtypes(include=np.number)

In [24]:
print(objectcols.shape)
print(numericcols.shape)

(53415, 12)
(53415, 24)


In [25]:
combinedf.dtypes

respondent_id                    int64
h1n1_concern                   float64
h1n1_knowledge                 float64
behavioral_antiviral_meds      float64
behavioral_avoidance           float64
behavioral_face_mask           float64
behavioral_wash_hands          float64
behavioral_large_gatherings    float64
behavioral_outside_home        float64
behavioral_touch_face          float64
doctor_recc_h1n1               float64
doctor_recc_seasonal           float64
chronic_med_condition          float64
child_under_6_months           float64
health_worker                  float64
health_insurance               float64
opinion_h1n1_vacc_effective    float64
opinion_h1n1_risk              float64
opinion_h1n1_sick_from_vacc    float64
opinion_seas_vacc_effective    float64
opinion_seas_risk              float64
opinion_seas_sick_from_vacc    float64
age_group                       object
education                       object
race                            object
sex                      

In [40]:
print(combinedf.shape)

(53415, 36)


In [41]:
numericcols.dtypes

respondent_id                    int64
h1n1_concern                   float64
h1n1_knowledge                 float64
behavioral_antiviral_meds      float64
behavioral_avoidance           float64
behavioral_face_mask           float64
behavioral_wash_hands          float64
behavioral_large_gatherings    float64
behavioral_outside_home        float64
behavioral_touch_face          float64
doctor_recc_h1n1               float64
doctor_recc_seasonal           float64
chronic_med_condition          float64
child_under_6_months           float64
health_worker                  float64
health_insurance               float64
opinion_h1n1_vacc_effective    float64
opinion_h1n1_risk              float64
opinion_h1n1_sick_from_vacc    float64
opinion_seas_vacc_effective    float64
opinion_seas_risk              float64
opinion_seas_sick_from_vacc    float64
household_adults               float64
household_children             float64
dtype: object

In [27]:
vaccinetrain=impdata.loc[0:26706,]
vaccinetest=impdata.loc[26707:53414,]

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
le=LabelEncoder()

In [30]:
vaccinetraindummy=vaccinetrain.apply(le.fit_transform)

In [31]:
vaccinetraindummy.head()

Unnamed: 0  h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
0           0             1               0                          0   
1           1             3               2                          0   
2           2             1               1                          0   
3           3             1               1                          0   
4           4             2               1                          0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                     0                     0                      0   
1                     1                     0                      1   
2                     1                     0                      0   
3                     1                     0                      1   
4                     1                     0                      1   

   behavioral_large_gatherings  behavioral_outside_home  \
0                            0                        1   
1                            0                        1   
2                            0                        0   
3                            1                        0   
4                            1                        0   

   behavioral_touch_face  ...  income_poverty  marital_status  rent_or_own  \
0                      1  ...               2               1            0   
1                      1  ...               2               1            1   
2                      0  ...               0               1            0   
3                      0  ...               2               1            1   
4                      1  ...               0               0            0   

   employment_status  hhs_geo_region  census_msa  household_adults  \
0                  1               8           2                 0   
1                  0               1           0                 0   
2                  0               9           0                 2   
3                  1               5           1                 0   
4                  0               9           0                 1   

   household_children  employment_industry  employment_occupation  
0                   0                    0                     18  
1                   0                   12                     19  
2                   0                   14                     21  
3                   0                   19                     13  
4                   0                   18                      5  

[5 rows x 36 columns]

In [34]:
vaccinetestdummy=vaccinetest.apply(le.fit_transform)

In [35]:
vaccinetestdummy

Unnamed: 0  h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
26707           0             2               2                          0   
26708           1             1               1                          0   
26709           2             2               2                          0   
26710           3             1               1                          0   
26711           4             3               1                          1   
...           ...           ...             ...                        ...   
53410       26703             1               1                          0   
53411       26704             3               1                          0   
53412       26705             0               1                          0   
53413       26706             3               1                          0   
53414       26707             2               1                          0   

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
26707                     1                     0                      1   
26708                     0                     0                      0   
26709                     0                     1                      1   
26710                     0                     0                      0   
26711                     1                     0                      1   
...                     ...                   ...                    ...   
53410                     1                     0                      1   
53411                     1                     0                      1   
53412                     0                     0                      0   
53413                     1                     0                      1   
53414                     0                     0                      1   

       behavioral_large_gatherings  behavioral_outside_home  \
26707                            1                        0   
26708                            0                        0   
26709                            1                        1   
26710                            0                        0   
26711                            1                        1   
...                            ...                      ...   
53410                            0                        0   
53411                            1                        1   
53412                            0                        0   
53413                            0                        1   
53414                            0                        0   

       behavioral_touch_face  ...  income_poverty  marital_status  \
26707                      1  ...               1               1   
26708                      0  ...               2               1   
26709                      1  ...               1               0   
26710                      0  ...               0               0   
26711                      1  ...               0               1   
...                      ...  ...             ...             ...   
53410                      1  ...               0               0   
53411                      1  ...               2               0   
53412                      0  ...               2               1   
53413                      0  ...               0               0   
53414                      1  ...               0               1   

       rent_or_own  employment_status  hhs_geo_region  census_msa  \
26707            1                  0               7           0   
26708            1                  0               1           2   
26709            0                  0               5           2   
26710            0                  1               5           0   
26711            0                  0               6           2   
...            ...                ...             ...         ...   
53410            0                  0               2           1   
53411            1 

In [36]:
vaccinetraindummy=pd.DataFrame(vaccinetraindummy)

In [37]:
vaccinetraindummy.head()

Unnamed: 0  h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
0           0             1               0                          0   
1           1             3               2                          0   
2           2             1               1                          0   
3           3             1               1                          0   
4           4             2               1                          0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                     0                     0                      0   
1                     1                     0                      1   
2                     1                     0                      0   
3                     1                     0                      1   
4                     1                     0                      1   

   behavioral_large_gatherings  behavioral_outside_home  \
0                            0                        1   
1                            0                        1   
2                            0                        0   
3                            1                        0   
4                            1                        0   

   behavioral_touch_face  ...  income_poverty  marital_status  rent_or_own  \
0                      1  ...               2               1            0   
1                      1  ...               2               1            1   
2                      0  ...               0               1            0   
3                      0  ...               2               1            1   
4                      1  ...               0               0            0   

   employment_status  hhs_geo_region  census_msa  household_adults  \
0                  1               8           2                 0   
1                  0               1           0                 0   
2                  0               9           0                 2   
3                  1               5           1                 0   
4                  0               9           0                 1   

   household_children  employment_industry  employment_occupation  
0                   0                    0                     18  
1                   0                   12                     19  
2                   0                   14                     21  
3                   0                   19                     13  
4                   0                   18                      5  

[5 rows x 36 columns]

In [38]:
vaccinetestdummy=pd.DataFrame(vaccinetestdummy)

In [39]:
vaccinetestdummy.head()

Unnamed: 0  h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
26707           0             2               2                          0   
26708           1             1               1                          0   
26709           2             2               2                          0   
26710           3             1               1                          0   
26711           4             3               1                          1   

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
26707                     1                     0                      1   
26708                     0                     0                      0   
26709                     0                     1                      1   
26710                     0                     0                      0   
26711                     1                     0                      1   

       behavioral_large_gatherings  behavioral_outside_home  \
26707                            1                        0   
26708                            0                        0   
26709                            1                        1   
26710                            0                        0   
26711                            1                        1   

       behavioral_touch_face  ...  income_poverty  marital_status  \
26707                      1  ...               1               1   
26708                      0  ...               2               1   
26709                      1  ...               1               0   
26710                      0  ...               0               0   
26711                      1  ...               0               1   

       rent_or_own  employment_status  hhs_geo_region  census_msa  \
26707            1                  0               7           0   
26708            1                  0               1           2   
26709            0                  0               5           2   
26710            0                  1               5           0   
26711            0                  0               6           2   

       household_adults  household_children  employment_industry  \
26707                 1                   0                    1   
26708                 3                   0                    1   
26709                 1                   0                   10   
26710                 1                   0                   18   
26711                 0                   1                    4   

       employment_occupation  
26707                      7  
26708                     20  
26709                     12  
26710                     15  
26711                     10  

[5 rows x 36 columns]

BINARY LOGISTIC REGRESSION 


In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
from sklearn.metrics import classification_report

In [22]:
logreg=LogisticRegression(max_iter=10000)

In [23]:
X=vaccinetraindummy
y=vaccine_labels.seasonal_vaccine

In [24]:
logregmodel=logreg.fit(X,y)

In [25]:
logregmodel.score(X,y)

0.7735799603100311

In [26]:
logregpredict=logregmodel.predict(X)

In [27]:
pd.crosstab(y,logregpredict)

col_0                 0     1
seasonal_vaccine             
0                 11536  2736
1                  3311  9124

In [28]:
(11536+9124)/(11536+2736+3311+6124)
#training accuracy from confusion matrix

0.8714725608470072

In [29]:
logregpredicttest=logregmodel.predict(vaccinetestdummy)

In [30]:
logregpredicttest

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

DECISION TREE

In [31]:
from sklearn.tree import DecisionTreeClassifier

In [32]:
tree=DecisionTreeClassifier(max_depth=10)

In [33]:
treemodel=tree.fit(X,y)

In [34]:
treemodel.score(X,y)

0.8156663047141199

In [35]:
treepredict=treemodel.predict(X)

In [36]:
print(classification_report(y,treepredict))

              precision    recall  f1-score   support

           0       0.82      0.84      0.83     14272
           1       0.81      0.79      0.80     12435

    accuracy                           0.82     26707
   macro avg       0.82      0.81      0.81     26707
weighted avg       0.82      0.82      0.82     26707



In [37]:
from sklearn.model_selection import cross_val_score

In [38]:
cross_val_score(tree,X,y,cv=5)

array([0.73755148, 0.73567952, 0.74405542, 0.75472758, 0.74630219])

RANDOM FOREST

In [39]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
RF=RandomForestClassifier(n_estimators=1000,oob_score=True)

In [41]:
RFmodel=RF.fit(X,y)

In [42]:
RFmodel.score(X,y)

1.0

In [43]:
RFpredict=RFmodel.predict(X)

In [44]:
RFpredict

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

In [45]:
pd.crosstab(y,RFpredict)

col_0                 0      1
seasonal_vaccine              
0                 14272      0
1                     0  12435

GRADIENT BOOSTING MACHINES (GBM)

In [46]:
from sklearn.ensemble import GradientBoostingClassifier

In [47]:
gbm=GradientBoostingClassifier(n_estimators=3000)

In [48]:
gbmmodel=gbm.fit(X,y)

In [49]:
gbmmodel.score(X,y)

0.8410903508443479

In [50]:
gbmpredict=gbmmodel.predict(X)

In [51]:
gbmpredict

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [52]:
pd.crosstab(y,gbmpredict)

col_0                 0      1
seasonal_vaccine              
0                 12212   2060
1                  2184  10251

In [53]:
print(classification_report(y,gbmpredict))

              precision    recall  f1-score   support

           0       0.85      0.86      0.85     14272
           1       0.83      0.82      0.83     12435

    accuracy                           0.84     26707
   macro avg       0.84      0.84      0.84     26707
weighted avg       0.84      0.84      0.84     26707



In [54]:
cross_val_score(gbm,X,y,cv=5)

array([0.76694122, 0.76244852, 0.77251451, 0.77532297, 0.77176559])

SUPPORT VECTOR MACHINES(SVM)

In [55]:
from sklearn.svm import SVC 

In [56]:
svm=SVC()

In [57]:
svmmodel=svm.fit(X,y)

In [58]:
svmmodel.score(X,y)

0.7793087954468866

In [59]:
svmpredict=svmmodel.predict(X)

In [60]:
svmpredict

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [61]:
pd.crosstab(y,svmpredict)

col_0                 0     1
seasonal_vaccine             
0                 11686  2586
1                  3308  9127

In [62]:
print(classification_report(y,svmpredict))

              precision    recall  f1-score   support

           0       0.78      0.82      0.80     14272
           1       0.78      0.73      0.76     12435

    accuracy                           0.78     26707
   macro avg       0.78      0.78      0.78     26707
weighted avg       0.78      0.78      0.78     26707



In [63]:
cross_val_score(svm,X,y,cv=5).mean()

0.774329030435073